name: Build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6
        with:
          submodules: recursive

      - name: Install dependencies
        run: |
          sudo apt-get update -q
          sudo apt-get install -y flex bison libboost-all-dev libfl-dev

      - name: Configure
        env:
          CC: clang
          CXX: clang++
        run: cmake -B build -DCMAKE_BUILD_TYPE=Release

      - name: Build
        run: cmake --build build --parallel $(nproc) --target dbms dbms_server dbms_client
